services:
  app:
    image: harbor.synclytic.app/te-emb-api/te-emb-service:1.0-alpine
    container_name: te_api_app
    hostname: te_api_app
    networks:
      - te_emb_service
    restart: always
    volumes:
      - ./data:/mnt/data
    env_file:
      - .env
    ports:
    - "3000:3000"
  redis:
    container_name: te_redis
    restart: always
    image: redis:7.2.5-alpine
    networks:
      - te_emb_service
    ports:
      - '6379:6379'
networks:
  te_emb_service:
    name: te_emb_service
    driver: bridge